name: Check
on: push
jobs:
  lint:
    runs-on: 'ubuntu-latest'
      steps: 
      -name: 'Checkout'
      uses: action/checkout@v3
      -name: install deps
      run: npm ci
      -name: lint
      run: npm run lint