name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      uses: action/checkout@v3
      -name: Checkout
      -name: install deps
      run: npm ci
      -name: lint
      run: npm run lint